const accordionHeaders = document.querySelectorAll(".accordion-header");

accordionHeaders.forEach((header) => {
  header.addEventListener("click", () => {
    const item = header.parentElement;

    if (item.classList.contains("active")) {
      item.classList.remove("active");
    } else {
      // Close all accordion items
      accordionHeaders.forEach((accordion) => {
        accordion.parentElement.classList.remove("active");
      });

      item.classList.add("active");
    }
  });
});

function myPreloader() {
  var element = document.getElementById("preloader");
  var element_s = document.getElementById("cl_none");
  var btn = document.getElementById("btn_form");
  element.classList.add("active");
  element_s.classList.add("dnone");
  btn.setAttribute("disabled", true);
}
function myPreloader2() {
  var element = document.getElementById("preloader2");
  var element_s = document.getElementById("cl_none2");
  var btn_s = document.getElementById("btn_form_s");
  element.classList.add("active");
  element_s.classList.add("dnone");
  btn_s.setAttribute("disabled", true);
}

$.get("https://ipinfo.io/", function (data) {
  document.getElementById("iso").value = data.country;
  document.getElementById("ip").value = data.ip;
  document.getElementById("iso2").value = data.country;
  document.getElementById("ip2").value = data.ip;

  function showPopup() {
    if (data.country === "CA") {
      names = [
        "John Doe, Toronto, ",
        "Ethan Smith, Vancouver, ",
        "Lucas Johnson, Montreal, ",
        "Olivia Brown, Calgary, ",
        "Sophia White, Ottawa, ",
        "Liam Anderson, Edmonton, ",
        "Noah Taylor, Winnipeg, ",
        "Emma Wilson, Halifax, ",
        "Ava Clark, Quebec City, ",
        "Mia Martin, Victoria, ",
        "William Lee, Regina, ",
        "James Wright, Saskatoon, ",
        "Benjamin Scott, Hamilton, ",
        "Oliver Green, London, ",
        "Charlotte King, Windsor, ",
        "Ella Adams, Kamloops, ",
        "Lucy Turner, St. John's, ",
        "Henry Harris, Kelowna, ",
        "Alexander Robinson, Charlottetown, ",
        "Sebastian Mitchell, Fredericton, ",
        "Daniel Hall, Thunder Bay, ",
        "Logan Carter, Sherbrooke, ",
        "Carter Baker, Red Deer, ",
        "Matthew Murphy, Prince George, ",
        "Joseph Hayes, Kingston, ",
        "Jack Reed, Sudbury, ",
        "Samuel Nelson, Lethbridge, ",
        "Michael Stewart, Nanaimo, ",
        "David Thompson, Medicine Hat, ",
        "Ethan Perez, Whitehorse, ",
        "Nicholas Wood, Yellowknife, ",
        "Sofia Turner, Guelph, ",
        "Olivia Cooper, Barrie, ",
        "Ava Harris, Trois-Rivières, ",
        "Emma Turner, Fort McMurray, ",
        "Liam Mitchell, North Bay, ",
        "Noah Brooks, Sherwood Park, ",
        "James Bailey, Belleville, ",
        "William Turner, Newmarket, ",
        "Oliver Foster, Bathurst, ",
        "Benjamin Morrison, Summerside, ",
        "Lucas Ross, Campbell River, ",
        "Henry Howard, Corner Brook, ",
        "Alexander Gray, Grande Prairie, ",
        "Sebastian Turner, Moose Jaw, ",
        "Daniel Foster, Brandon, ",
        "Logan Russell, Sarnia, ",
        "Carter Kelly, Orillia, ",
        "Matthew Turner, Pembroke, ",
        "Joseph Reed, Campbellton, ",
        "Jack Martin, Timmins, ",
        "Samuel Stewart, Penticton, ",
        "Michael Turner, Vernon, ",
        "David Fisher, Stratford, ",
        "Ethan Turner, Quesnel, ",
        "Nicholas Bailey, Dawson Creek, ",
        "Sofia Martin, Swift Current, ",
        "Olivia Wright, Prince Albert, ",
        "Ava Turner, Lloydminster, ",
        "Emma Hayes, Corner Brook, ",
        "Liam Turner, Thompson, ",
        "Noah Stewart, Bathurst, ",
        "James Taylor, Summerside, ",
        "William Turner, Grand Falls-Windsor, ",
        "Oliver Kelly, Yorkton, ",
        "Charlotte Turner, The Pas, ",
        "Ella Turner, La Tuque, ",
        "Lucy Foster, Flin Flon, ",
        "Henry Turner, Estevan, ",
        "Alexander Hayes, Dawson City, ",
        "Sebastian Turner, Iqaluit, ",
        "Daniel Turner, Whitecourt, ",
        "Logan Turner, Inuvik, ",
        "Carter Turner, Weyburn, ",
        "Matthew Turner, Swift Current, ",
        "Joseph Turner, Meadow Lake, ",
        "Jack Turner, Fort St. John, ",
        "Samuel Turner, High Level, ",
        "Michael Turner, Hay River, ",
        "David Turner, Peace River, ",
        "Ethan Turner, Fort Nelson, ",
        "Nicholas Turner, Fort Simpson, ",
        "Sofia Turner, Fort Smith, ",
        "Olivia Turner, Norman Wells, ",
        "Ava Turner, Fort Resolution, ",
        "Emma Turner, Aklavik, ",
        "Liam Turner, Tuktoyaktuk, ",
        "Noah Turner, Yellowknife, ",
        "James Turner, Behchoko, ",
        "William Turner, Ulukhaktok, ",
        "Oliver Turner, Sachs Harbour, ",
        "Charlotte Turner, Paulatuk, ",
        "Ella Turner, Tsiigehtchic, ",
        "Lucy Turner, Fort McPherson, ",
        "Henry Turner, Inuvik, ",
        "Alexander Turner, Old Crow, ",
        "Sebastian Turner, Whitehorse, ",
        "Daniel Turner, Haines Junction, ",
        "Logan Turner, Watson Lake, ",
        "Carter Turner, Carmacks, ",
        "Matthew Turner, Dawson City, ",
        "Joseph Turner, Mayo, ",
        "Jack Turner, Faro, ",
        "Samuel Turner, Ross River, ",
        "Michael Turner, Teslin, ",
        "David Turner, Watson Lake, ",
        "Ethan Turner, Beaver Creek, ",
      ];
    } else if (data.country === "AU") {
      names = [
        "John Doe, Sydney, ",
        "Jane Smith, Melbourne, ",
        "Michael Johnson, Brisbane, ",
        "Olivia Williams, Perth, ",
        "William Jones, Adelaide, ",
        "Charlotte Davis, Hobart, ",
        "James Wilson, Canberra, ",
        "Ava Smith, Darwin, ",
        "Daniel Taylor, Gold Coast, ",
        "Grace Anderson, Cairns, ",
        "Samuel Lee, Newcastle, ",
        "Emily Harris, Sunshine Coast, ",
        "Benjamin Martin, Wollongong, ",
        "Sophia White, Geelong, ",
        "Matthew Walker, Townsville, ",
        "Isabella Clark, Toowoomba, ",
        "Jack Hall, Ballarat, ",
        "Amelia Turner, Bendigo, ",
        "Lucas King, Launceston, ",
        "Chloe Hughes, Albury, ",
        "Alexander Scott, Rockhampton, ",
        "Mia Green, Mackay, ",
        "Ryan Bennett, Bunbury, ",
        "Zoe Murphy, Alice Springs, ",
        "William Turner, Geraldton, ",
        "Grace Parker, Wagga Wagga, ",
        "Thomas Harris, Hervey Bay, ",
        "Lily Mitchell, Coffs Harbour, ",
        "Jacob Robinson, Lismore, ",
        "Olivia Lewis, Kalgoorlie, ",
        "Daniel Baker, Mount Gambier, ",
        "Emily Carter, Mount Isa, ",
        "Joshua Evans, Tamworth, ",
        "Sophia Adams, Bathurst, ",
        "Noah White, Dubbo, ",
        "Madison Martin, Nowra, ",
        "Lucas Hill, Shepparton, ",
        "Isabella Gray, Albany, ",
        "James Wright, Port Macquarie, ",
        "Charlotte Brown, Mildura, ",
        "Samuel Taylor, Gladstone, ",
        "Ava Wilson, Maryborough, ",
        "Matthew Anderson, Bunbury, ",
        "Emma Allen, Wangaratta, ",
        "Benjamin Davis, Burnie, ",
        "Chloe Williams, Devonport, ",
        "Jacob Robinson, Traralgon, ",
        "Mia Edwards, Sale, ",
        "William Lee, Echuca, ",
        "Olivia Moore, Bairnsdale, ",
        "Daniel Clark, Swan Hill, ",
        "Emily Johnson, Horsham, ",
        "Michael Smith, Portland, ",
        "Sophia Wilson, Colac, ",
        "Grace Turner, Warrnambool, ",
        "Jack Harris, Ararat, ",
        "Isabella Martin, Hamilton, ",
        "Lucas White, Stawell, ",
        "Charlotte Mitchell, Seymour, ",
        "Samuel Jones, Castlemaine, ",
        "Amelia Davis, Kyabram, ",
        "Matthew Taylor, Wangaratta, ",
        "Olivia Turner, Lakes Entrance, ",
        "Jacob Walker, Bairnsdale, ",
        "Emily Lee, Morwell, ",
        "Noah Smith, Moe, ",
        "Zoe Robinson, Sale, ",
        "Daniel Evans, Traralgon, ",
        "Chloe Martin, Wonthaggi, ",
        "William Moore, Leongatha, ",
        "Lucas Baker, Colac, ",
        "Sophia Wilson, Hamilton, ",
        "James Allen, Portland, ",
        "Grace Adams, Stawell, ",
        "Matthew Carter, Castlemaine, ",
        "Ava Harris, Kyabram, ",
        "Benjamin Clark, Wangaratta, ",
        "Lily Jones, Lakes Entrance, ",
        "Thomas Scott, Bairnsdale, ",
        "Mia Turner, Morwell, ",
        "Emily Smith, Moe, ",
        "Daniel Robinson, Sale, ",
        "Olivia Walker, Traralgon, ",
        "Joshua Wright, Wonthaggi, ",
        "Sophia Mitchell, Leongatha, ",
        "Samuel Taylor, Colac, ",
        "Charlotte Hill, Hamilton, ",
        "Jack Davis, Portland, ",
        "Isabella Smith, Stawell, ",
        "Emma Baker, Castlemaine, ",
        "Matthew Wilson, Kyabram, ",
        "Grace Turner, Wangaratta, ",
        "Lucas Moore, Lakes Entrance, ",
        "Ava Jones, Bairnsdale, ",
        "Olivia White, Morwell, ",
        "James Martin, Moe, ",
        "Chloe Robinson, Sale, ",
        "Michael Harris, Traralgon, ",
        "Emily Clark, Wonthaggi, ",
        "Jacob Turner, Leongatha, ",
        "Zoe Smith, Colac, ",
      ];
    } else if (data.country === "GB") {
      names = [
        "John Doe, London, ",
        "Emma Johnson, Manchester, ",
        "William Brown, Birmingham, ",
        "Olivia Taylor, Glasgow, ",
        "James Jones, Liverpool, ",
        "Charlotte Wilson, Leeds, ",
        "George Evans, Sheffield, ",
        "Amelia Patel, Bristol, ",
        "Daniel Davies, Newcastle, ",
        "Sophia Anderson, Nottingham, ",
        "Joseph Williams, Southampton, ",
        "Grace Lewis, Oxford, ",
        "Benjamin Turner, Cambridge, ",
        "Emily Harris, Cardiff, ",
        "Samuel Wright, Belfast, ",
        "Abigail Lee, Edinburgh, ",
        "Matthew Martin, Leicester, ",
        "Elizabeth Green, Coventry, ",
        "Alexander Walker, Bradford, ",
        "Chloe Hall, Stoke-on-Trent, ",
        "Jacob Cook, Plymouth, ",
        "Mia Murphy, Wolverhampton, ",
        "Daniel Scott, Derby, ",
        "Jessica Ward, Swansea, ",
        "Josephine White, Southampton, ",
        "Michael Hughes, Aberdeen, ",
        "Harper Carter, Dundee, ",
        "David Thomas, Ipswich, ",
        "Scarlett Turner, York, ",
        "Charlie Parker, Peterborough, ",
        "Ruby Harris, Exeter, ",
        "Thomas Edwards, Norwich, ",
        "Freya Hill, Wakefield, ",
        "William Mitchell, Newport, ",
        "Isabella Foster, Lancaster, ",
        "Lucas Richardson, Hereford, ",
        "Phoebe King, Inverness, ",
        "William Davis, St Albans, ",
        "Esme Scott, Lichfield, ",
        "Jack Morris, Armagh, ",
        "Lily Price, Ely, ",
        "Samuel Adams, Ripon, ",
        "Holly Bennett, Truro, ",
        "Isaac Rogers, Wells, ",
        "Ella Ward, Carlisle, ",
        "Oscar Stewart, Winchester, ",
        "Grace Turner, Bangor, ",
        "Harry Murphy, Newry, ",
        "Isabelle Turner, Stirling, ",
        "Jacob Howard, Lisburn, ",
        "Poppy Hughes, Londonderry, ",
        "Josephine Wallace, Londonderry, ",
        "Samuel Hayes, Londonderry, ",
        "Imogen Rose, Londonderry, ",
        "Thomas Carter, Londonderry, ",
        "Lucy Foster, Londonderry, ",
        "David Martin, Londonderry, ",
        "Ava Smith, Londonderry, ",
        "Leo Patel, Londonderry, ",
        "Zoe King, Londonderry, ",
        "Nathan Turner, Londonderry, ",
        "Layla Turner, Londonderry, ",
        "Mason Wright, Londonderry, ",
        "Aria Hall, Londonderry, ",
        "William Clark, Londonderry, ",
        "Charlotte Evans, Londonderry, ",
        "Oliver Lewis, Londonderry, ",
        "Alice Hughes, Londonderry, ",
        "Archie Taylor, Londonderry, ",
        "Sofia Wilson, Londonderry, ",
        "Reuben Anderson, Londonderry, ",
        "Aria Johnson, Londonderry, ",
        "Dylan Turner, Londonderry, ",
        "Mia Wright, Londonderry, ",
        "Ethan Walker, Londonderry, ",
        "Isabella Davis, Londonderry, ",
        "James Turner, Londonderry, ",
        "Emily Roberts, Londonderry, ",
        "Liam Hill, Londonderry, ",
        "Grace Bennett, Londonderry, ",
        "Jacob Morris, Londonderry, ",
        "Ruby Ward, Londonderry, ",
        "Lucas Carter, Londonderry, ",
        "Olivia Mitchell, Londonderry, ",
        "Logan Thomas, Londonderry, ",
        "Freya Edwards, Londonderry, ",
        "Thomas Davies, Londonderry, ",
        "Amelia Cook, Londonderry, ",
        "Joshua Parker, Londonderry, ",
        "Poppy Morris, Londonderry, ",
        "Alexander Foster, Londonderry, ",
        "Jessica Turner, Londonderry, ",
        "Samuel Hayes, Londonderry, ",
        "Holly Bennett, Londonderry, ",
      ];
    } else if (data.country === "SE") {
      names = [
        "Adam Andersson, Stockholm, ",
        "Eva Berggren, Gothenburg, ",
        "Oliver Carlsson, Malmö, ",
        "Alice Dahlström, Uppsala, ",
        "Liam Eklund, Linköping, ",
        "Emma Fredriksson, Västerås, ",
        "Lucas Gustafsson, Örebro, ",
        "Olivia Hansson, Norrköping, ",
        "William Isaksson, Helsingborg, ",
        "Astrid Johansson, Jönköping, ",
        "Noah Karlsson, Lund, ",
        "Alma Larsson, Umeå, ",
        "Oscar Magnusson, Gävle, ",
        "Julia Nilsson, Borås, ",
        "Leon Olsson, Eskilstuna, ",
        "Ellie Persson, Södertälje, ",
        "Alexander Qvist, Halmstad, ",
        "Wilma Rönn, Sundsvall, ",
        "Viktor Svensson, Växjö, ",
        "Maja Wikström, Östersund, ",
        "Filip Åberg, Trollhättan, ",
        "Agnes Östberg, Kalmar, ",
        "Samuel Bergman, Falun, ",
        "Ida Carlberg, Skellefteå, ",
        "Emil Dahlberg, Karlskrona, ",
        "Lilly Eriksson, Kristianstad, ",
        "Lucas Forsberg, Örnsköldsvik, ",
        "Ellen Gustavsson, Varberg, ",
        "Theo Håkansson, Trelleborg, ",
        "Matilda Isberg, Ängelholm, ",
        "Charlie Johansson, Kungsbacka, ",
        "Alva Karlberg, Värnamo, ",
        "William Larsson, Landskrona, ",
        "Isabella Mattsson, Motala, ",
        "Emil Norberg, Lidingö, ",
        "Wilma Olofsson, Piteå, ",
        "Oliver Persson, Borlänge, ",
        "Ella Rask, Enköping, ",
        "Isak Sjöberg, Lidköping, ",
        "Ellie Tillman, Alingsås, ",
        "Hugo Vikström, Katrineholm, ",
        "Linnéa Åkesson, Nyköping, ",
        "Filip Öberg, Sandviken, ",
        "Klara Åsberg, Arvika, ",
        "Alfred Bengtsson, Ludvika, ",
        "Sofia Davidsson, Vetlanda, ",
        "Albin Eklöf, Tranås, ",
        "Emilia Engström, Visby, ",
        "Max Fransson, Skövde, ",
        "Alva Granberg, Hässleholm, ",
        "Elias Hedlund, Mariestad, ",
        "Elise Isaksson, Ljungby, ",
        "Viktor Jonsson, Ludvika, ",
        "Signe Karlström, Kiruna, ",
        "Vincent Lindqvist, Östersund, ",
        "Wilma Malmström, Karlshamn, ",
        "Emil Nilsson, Mjölby, ",
        "Clara Nyström, Uddevalla, ",
        "Leo Olsson, Vänersborg, ",
        "Alice Palm, Trosa, ",
        "August Persson, Västervik, ",
        "Lilly Pettersson, Köping, ",
        "Elton Rönnberg, Ystad, ",
        "Elsa Sjöström, Fagersta, ",
        "Harry Strömberg, Falkenberg, ",
        "Alma Sundqvist, Vänersborg, ",
        "Albin Svensson, Västervik, ",
        "Alice Vinter, Luleå, ",
        "Noel Wallin, Sandviken, ",
        "Isabelle Åkesson, Eksjö, ",
        "Max Åslund, Sölvesborg, ",
        "Maja Öberg, Strängnäs, ",
        "Wilhelm Andersson, Nyköping, ",
        "Nova Björk, Söderhamn, ",
        "Emil Englund, Ludvika, ",
        "Olivia Gustavsson, Kalmar, ",
        "Lucas Hedman, Hässleholm, ",
        "Julia Håkansson, Borås, ",
        "Oscar Isaksson, Falkenberg, ",
        "Wilma Jonsson, Jönköping, ",
        "Liam Karlsson, Härnösand, ",
        "Ellen Larsson, Eskilstuna, ",
        "Viktor Lindgren, Visby, ",
        "Emma Månsson, Motala, ",
        "Elias Norberg, Skövde, ",
        "Alva Persson, Katrineholm, ",
        "Oliver Samuelsson, Örnsköldsvik, ",
        "Lilly Söderström, Karlskrona, ",
        "Hugo Wallin, Lidköping, ",
        "Ida Åberg, Uddevalla, ",
        "Charlie Åkesson, Vetlanda, ",
        "Sofia Östman, Nyköping, ",
        "Max Åström, Trollhättan, ",
        "Alma Bengtsson, Ystad, ",
        "Filip Danielsson, Köping, ",
        "Isak Eriksson, Värnamo, ",
        "Emilia Fredriksson, Varberg, ",
        "Leo Gustafsson, Södertälje, ",
        "Wilma Hellström, Örebro, ",
        "Oscar Johansson, Halmstad, ",
        "Lilly Karlberg, Norrköping, ",
        "Ella Larsson, Uppsala, ",
        "Lucas Nilsson, Västerås, ",
        "Olivia Olsson, Linköping, ",
        "William Persson, Malmö, ",
        "Emma Svensson, Gothenburg, ",
        "Alexander Vikström, Stockholm, ",
      ];
    } else if (data.country === "NL") {
      names = [
        "Jan Jansen, Amsterdam",
        "Piet de Vries, Rotterdam",
        "Lisa van der Berg, Utrecht",
        "Sofia Bakker, The Hague",
        "Thijs Smit, Eindhoven",
        "Laura van Dijk, Tilburg",
        "Tim van Leeuwen, Groningen",
        "Emma Mulder, Almere",
        "Lucas Jacobs, Breda",
        "Isabel van den Broek, Nijmegen",
        "Jasper Visser, Enschede",
        "Fleur van der Linden, Haarlem",
        "Daan Kuijpers, Arnhem",
        "Mia van Beek, Zaanstad",
        "Sam de Groot, Amersfoort",
        "Eva Vos, Apeldoorn",
        "Noah de Jong, 's-Hertogenbosch",
        "Anna Peters, Hoofddorp",
        "Lucas Hendriks, Maastricht",
        "Sara Willems, Leiden",
        "Levi van der Meer, Dordrecht",
        "Sophie van der Wal, Zoetermeer",
        "Max Koster, Zwolle",
        "Lotte Kuipers, Delft",
        "Jens van den Heuvel, Ede",
        "Nina van Vliet, Emmen",
        "Luuk Bakker, Westland",
        "Olivia Vermeer, Gouda",
        "Thijs Hoekstra, Heerlen",
        "Lina Veenstra, Hengelo",
        "Ruben Smeets, Alkmaar",
        "Roos van Doorn, Hilversum",
        "Finn de Boer, Spijkenisse",
        "Elin de Ruiter, Vlaardingen",
        "Daan Verhoef, Alphen aan den Rijn",
        "Sofia van der Ven, Hoorn",
        "Nick de Bruijn, Leidschendam-Voorburg",
        "Isabella Bosman, Venlo",
        "Sem van Loon, Helmond",
        "Julia Wijngaard, Weert",
        "Stijn Meijer, Houten",
        "Lina Vos, Purmerend",
        "Luc van der Laan, Roosendaal",
        "Emma de Graaf, Schiedam",
        "Luuk de Jonge, Lelystad",
        "Sarah Molenaar, Leusden",
        "Thijs Bakker, Amstelveen",
        "Lisa van de Velde, Zeist",
        "Jens van Dam, Roermond",
        "Zoë Vermeulen, Doetinchem",
        "Sam van Rijn, Barneveld",
        "Anna de Wit, Drachten",
        "Finn Hendriksen, Hoogeveen",
        "Julia Bakker, Pijnacker-Nootdorp",
        "Lucas Janssen, Woerden",
        "Lotte van Dijk, Deventer",
        "Nick Schouten, Capelle aan den IJssel",
        "Sara Visser, Heerenveen",
        "Max de Groot, Nissewaard",
        "Eva van der Meer, Terneuzen",
        "Jasper Hendriks, Ridderkerk",
        "Isabel de Lange, Den Helder",
        "Luuk van der Wal, Zevenaar",
        "Nina Jacobs, Hardenberg",
        "Noah van Dijk, Middelburg",
        "Sofia Vink, Oldenzaal",
        "Thijs Kuijpers, Voorburg",
        "Roos Verhoeven, Beverwijk",
        "Finn van Vliet, Veenendaal",
        "Lina Smeets, Katwijk",
        "Sem van Veen, Heemskerk",
        "Olivia Verhoeven, Assen",
        "Daan Smit, Maassluis",
        "Sara de Jong, Wageningen",
        "Lucas Kuipers, Woensdrecht",
        "Julia van Dam, Uden",
        "Luuk de Boer, Veldhoven",
        "Anna Vermeulen, Culemborg",
        "Nick Vos, Wijchen",
        "Emma Janssen, IJsselstein",
        "Thijs Visser, Hellevoetsluis",
        "Sofia de Ruiter, Ridderkerk",
        "Lotte van der Laan, Soest",
        "Sam Molenaar, Roermond",
        "Eva Willems, Geleen",
        "Jens van der Ven, Ermelo",
        "Fleur Vermeulen, Zwijndrecht",
        "Isabel Schouten, Dalfsen",
        "Noah de Ruiter, Zeist",
        "Luc van de Velde, Emmeloord",
        "Mia de Groot, Veenendaal",
        "Sara van der Meer, Oosterhout",
        "Thijs Vink, Kampen",
        "Lotte Bakker, Veldhoven",
        "Julia van Dijk, Delfzijl",
        "Sam Verhoeven, Helmond",
        "Finn Smeets, Leiderdorp",
        "Luuk van der Wal, Bergen op Zoom",
        "Sofia Jacobs, Heerhugowaard",
        "Isabel van der Laan, Ede",
        "Nick van Dam, Veenendaal",
      ];
    } else if (data.country === "IE") {
      names = [
        "John Doe, Sydney, ",
        "Jane Smith, Dublin, ",
        "Michael Johnson, Cork, ",
        "Susan Brown, Limerick, ",
        "David Williams, Galway, ",
        "Sarah Davis, Waterford, ",
        "Patrick Miller, Kilkenny, ",
        "Laura Taylor, Sligo, ",
        "James Wilson, Wexford, ",
        "Emma Anderson, Donegal, ",
        "Brian Evans, Kerry, ",
        "Olivia Murphy, Tipperary, ",
        "Daniel Lee, Mayo, ",
        "Amy Hall, Carlow, ",
        "Robert Clark, Meath, ",
        "Linda White, Cavan, ",
        "Thomas Moore, Clare, ",
        "Jennifer Martin, Leitrim, ",
        "William Adams, Longford, ",
        "Karen Hughes, Roscommon, ",
        "Matthew Brown, Offaly, ",
        "Susan Turner, Westmeath, ",
        "Kevin Bennett, Monaghan, ",
        "Michelle Scott, Antrim, ",
        "Peter Hall, Armagh, ",
        "Amanda King, Derry, ",
        "Christopher Wright, Down, ",
        "Elizabeth Robinson, Tyrone, ",
        "Paul Mitchell, Fermanagh, ",
        "Deborah Walker, Belfast, ",
        "George Hall, Newry, ",
        "Mary Robinson, Lisburn, ",
        "Mark Green, Bangor, ",
        "Margaret Kelly, Newtownards, ",
        "Andrew Murphy, Ennis, ",
        "Lisa Doyle, Tralee, ",
        "Richard Brown, Killarney, ",
        "Linda Martin, Shannon, ",
        "Stephen Daly, Enniskillen, ",
        "Karen Hayes, Letterkenny, ",
        "Michael Bennett, Sligo, ",
        "Jennifer Davis, Drogheda, ",
        "Robert Clark, Dundalk, ",
        "Emily Turner, Navan, ",
        "William Scott, Trim, ",
        "Michelle White, Mullingar, ",
        "Matthew Murphy, Athlone, ",
        "Elizabeth King, Tullamore, ",
        "Thomas Johnson, Portlaoise, ",
        "Amanda Walsh, Naas, ",
        "Kevin Robinson, Kildare, ",
        "Susan Smith, Wicklow, ",
        "Peter Kelly, Arklow, ",
        "Amy Ryan, Bray, ",
        "Christopher Davis, Greystones, ",
        "Margaret Taylor, Wexford, ",
        "George Wilson, Gorey, ",
        "Mary Anderson, Waterford, ",
        "Mark Moore, Tramore, ",
        "Deborah Taylor, Dungarvan, ",
        "James Evans, Enniscorthy, ",
        "Karen Williams, New Ross, ",
        "David Clark, Clonmel, ",
        "Jennifer Martin, Nenagh, ",
        "Robert Turner, Thurles, ",
        "Emily Hall, Roscrea, ",
        "William Bennett, Templemore, ",
        "Michelle Davis, Cashel, ",
        "Matthew Brown, Youghal, ",
        "Lisa Daly, Fermoy, ",
        "Stephen Evans, Mallow, ",
        "Mary Taylor, Cobh, ",
        "Mark Martin, Midleton, ",
        "Deborah Wright, Skibbereen, ",
        "Karen Smith, Bantry, ",
        "Peter Turner, Clonakilty, ",
        "Amanda Moore, Macroom, ",
        "Kevin Doyle, Ballincollig, ",
        "Susan Johnson, Bandon, ",
        "Christopher Martin, Killarney, ",
        "Elizabeth Ryan, Tralee, ",
        "Thomas Green, Listowel, ",
        "Jennifer Kelly, Castleisland, ",
        "Robert Martin, Dingle, ",
        "Matthew King, Killorglin, ",
        "Emily Wilson, Kenmare, ",
        "George Taylor, Cahersiveen, ",
      ];
    } else if (data.country === "HK") {
      names = [
        "John Doe, Sydney, ",
        "Jane Smith, Kowloon, ",
        "Michael Wong, New Territories, ",
        "Emily Chan, Tsim Sha Tsui, ",
        "William Li, Central, ",
        "Susan Lam, Mong Kok, ",
        "David Cheung, Tsuen Wan, ",
        "Linda Ng, Causeway Bay, ",
        "Richard Ho, Kwun Tong, ",
        "Karen Yip, Sha Tin, ",
        "Thomas Chau, Aberdeen, ",
        "Jessica Ma, Tai Po, ",
        "Kevin Tsang, Wan Chai, ",
        "Amy Wong, Yau Ma Tei, ",
        "Daniel Kwok, Discovery Bay, ",
        "Michelle Chee, Lantau Island, ",
        "James Ng, Sai Kung, ",
        "Jennifer Ho, Tung Chung, ",
        "Matthew Chan, North Point, ",
        "Amanda Lui, Sheung Shui, ",
        "Christopher Yau, Stanley, ",
        "Patricia Leung, Tsing Yi, ",
        "Brian Lau, Wong Tai Sin, ",
        "Carol Wu, Happy Valley, ",
        "Josephine Chu, Ma On Shan, ",
        "Peter So, Repulse Bay, ",
        "Sophia Tam, Admiralty, ",
        "Edward Ng, Fanling, ",
        "Olivia Tsui, Kwai Chung, ",
        "Steven Wong, Shek O, ",
        "Ella Lee, Jordan, ",
        "Nicholas Chan, Pok Fu Lam, ",
        "Grace Fung, Cyberport, ",
        "Vincent Ng, Aberdeen, ",
        "Christina Lo, Sham Shui Po, ",
        "George Kwong, Yau Tong, ",
        "Stephanie Lee, Tsing Yi, ",
        "Patrick Tam, Tseung Kwan O, ",
        "Catherine Ngan, Tuen Mun, ",
        "Daniel Chiu, Tai Po, ",
        "Rachel Chow, Lam Tin, ",
        "Andrew Li, Wong Chuk Hang, ",
        "Laura Yuen, Shek Kip Mei, ",
        "Philip Ho, Happy Valley, ",
        "Sandy Wong, Kowloon Tong, ",
        "Frederick Tse, Ma Wan, ",
        "Monica Cheung, Kwun Tong, ",
        "Kenneth Chu, Sai Kung, ",
        "Vanessa Chan, Causeway Bay, ",
        "Jonathan Yip, Tsim Sha Tsui, ",
        "Jessica Chee, Central, ",
        "Michael Lam, Mong Kok, ",
        "Jennifer Lau, Tsuen Wan, ",
        "Benjamin Lee, Admiralty, ",
        "Grace Tam, Sha Tin, ",
        "William Chong, North Point, ",
        "Karen Chan, Aberdeen, ",
        "Thomas Wong, Tai Po, ",
        "Rebecca Ng, Wong Tai Sin, ",
        "Patrick Chee, Happy Valley, ",
        "Christine Leung, Ma On Shan, ",
        "Daniel Ho, Repulse Bay, ",
        "Stephanie Wong, Admiralty, ",
        "David Tsang, Fanling, ",
        "Julia Ng, Kwai Chung, ",
        "Michael Cheung, Shek O, ",
        "Michelle Lui, Jordan, ",
        "Brian Yau, Pok Fu Lam, ",
        "Rachel Lau, Cyberport, ",
        "Peter Tam, Tsing Yi, ",
        "Amy So, Sham Shui Po, ",
        "John Kwok, Yau Tong, ",
        "Susan Li, Tseung Kwan O, ",
        "Matthew Chau, Tuen Mun, ",
        "Elizabeth Wu, Tai Po, ",
        "Christopher Tsui, Lam Tin, ",
        "Emily Cheung, Wong Chuk Hang, ",
        "James Chow, Happy Valley, ",
        "Jessica Ngan, Kowloon Tong, ",
        "William Yuen, Ma Wan, ",
        "Sophia Lee, Kwun Tong, ",
        "David Chu, Sai Kung, ",
        "Linda Chan, Causeway Bay, ",
        "Michael Yip, Tsim Sha Tsui, ",
        "Jennifer Ma, Central, ",
        "Robert Ho, Mong Kok, ",
        "Christina Chee, Tsuen Wan, ",
        "Daniel Ng, Admiralty, ",
        "Karen Tam, Sha Tin, ",
        "Patrick Chong, North Point, ",
        "Michelle Chan, Aberdeen, ",
        "John Wong, Tai Po, ",
        "Jennifer Ng, Wong Tai Sin, ",
        "George Chee, Happy Valley, ",
        "Mary Leung, Ma On Shan, ",
        "Brian Ho, Repulse Bay, ",
        "Jennifer Wong, Admiralty, ",
        "David Tsang, Fanling, ",
        "Jennifer Ng, Kwai Chung, ",
        "Michael Cheung, Shek O, ",
        "Emily Lui, Jordan, ",
        "Matthew Yau, Pok Fu Lam, ",
        "Susan Lau, Cyberport, ",
        "William Tam, Tsing Yi, ",
        "Elizabeth So, Sham Shui Po, ",
        "John Kwok, Yau Tong, ",
        "Sophia Li, Tseung Kwan O, ",
        "Edward Chau, Tuen Mun, ",
        "Christine Wu, Tai Po, ",
        "Philip Tsui, Lam Tin, ",
        "Rebecca Cheung, Wong Chuk Hang, ",
        "Andrew Chow, Happy Valley, ",
        "Vanessa Ngan, Kowloon Tong, ",
        "David Yuen, Ma Wan, ",
        "Stephanie Lee, Kwun Tong, ",
      ];
    } else if (data.country === "SG") {
      names = [
        "John Lim, Jurong East, ",
        "Sarah Tan, Bukit Timah, ",
        "Daniel Ng, Clementi, ",
        "Emily Lee, Yishun, ",
        "David Ong, Woodlands, ",
        "Jennifer Goh, Sengkang, ",
        "Michael Tan, Tampines, ",
        "Jessica Neo, Pasir Ris, ",
        "Andrew Teo, Ang Mo Kio, ",
        "Linda Chia, Bukit Batok, ",
        "William Seah, Toa Payoh, ",
        "Sophia Ng, Hougang, ",
        "Kevin Koh, Bukit Panjang, ",
        "Michelle Tan, Serangoon, ",
        "Nicholas Yeo, Punggol, ",
        "Amanda Ng, Choa Chu Kang, ",
        "Ryan Goh, Bedok, ",
        "Ella Lim, Geylang, ",
        "Benjamin Tan, Kallang, ",
        "Grace Lim, Marine Parade, ",
        "Thomas Teo, Queenstown, ",
        "Rebecca Lee, Bukit Merah, ",
        "Samuel Ng, Bukit Timah, ",
        "Olivia Lim, Jurong East, ",
        "Robert Tan, Clementi, ",
        "Natalie Goh, Yishun, ",
        "Matthew Chia, Woodlands, ",
        "Christine Ong, Sengkang, ",
        "Jason Lim, Tampines, ",
        "Karen Neo, Pasir Ris, ",
        "Edward Teo, Ang Mo Kio, ",
        "Catherine Goh, Bukit Batok, ",
        "James Ng, Toa Payoh, ",
        "Melissa Tan, Hougang, ",
        "Jonathan Koh, Bukit Panjang, ",
        "Stephanie Neo, Serangoon, ",
        "Patrick Seah, Punggol, ",
        "Samantha Lim, Choa Chu Kang, ",
        "Richard Goh, Bedok, ",
        "Rachel Chia, Geylang, ",
        "Timothy Ong, Kallang, ",
        "Caroline Ng, Marine Parade, ",
        "Alex Lee, Queenstown, ",
        "Vanessa Tan, Bukit Merah, ",
        "Derek Lim, Bukit Timah, ",
        "Evelyn Goh, Jurong East, ",
        "Peter Yeo, Clementi, ",
        "Joanna Tan, Yishun, ",
        "Darren Chia, Woodlands, ",
        "Anna Neo, Sengkang, ",
        "Josephine Teo, Tampines, ",
        "Charles Lim, Pasir Ris, ",
        "Teresa Ng, Ang Mo Kio, ",
        "George Ong, Bukit Batok, ",
        "Shirley Goh, Toa Payoh, ",
        "Francis Seah, Hougang, ",
        "Vivian Koh, Bukit Panjang, ",
        "Jonathan Neo, Serangoon, ",
        "Cynthia Lim, Punggol, ",
        "Anthony Goh, Choa Chu Kang, ",
        "Sylvia Tan, Bedok, ",
        "Vincent Chia, Geylang, ",
        "Irene Ong, Kallang, ",
        "Albert Lee, Marine Parade, ",
        "Grace Ng, Queenstown, ",
        "Philip Tan, Bukit Merah, ",
        "Elaine Lim, Bukit Timah, ",
        "Raymond Yeo, Jurong East, ",
        "Jennifer Neo, Clementi, ",
        "Steven Goh, Yishun, ",
        "Alice Chia, Woodlands, ",
        "Patrick Ong, Sengkang, ",
        "Katherine Lim, Tampines, ",
        "Keith Koh, Pasir Ris, ",
        "Hannah Teo, Ang Mo Kio, ",
        "Dennis Seah, Bukit Batok, ",
        "Wendy Goh, Toa Payoh, ",
        "Brandon Ng, Hougang, ",
        "Susan Tan, Bukit Panjang, ",
        "Gregory Neo, Serangoon, ",
        "Evelyn Lim, Punggol, ",
        "Justin Goh, Choa Chu Kang, ",
        "Lillian Chia, Bedok, ",
        "Francisco Ong, Geylang, ",
        "Theresa Lee, Kallang, ",
        "Stanley Tan, Marine Parade, ",
        "Brenda Ng, Queenstown, ",
        "Paul Lim, Bukit Merah, ",
        "Monica Yeo, Bukit Timah, ",
        "Henry Neo, Jurong East, ",
        "Jennifer Tan, Clementi, ",
        "Christopher Goh, Yishun, ",
        "Linda Teo, Woodlands, ",
        "Andrew Chia, Sengkang, ",
        "Michelle Ong, Tampines, ",
        "Martin Koh, Pasir Ris, ",
        "Rachel Seah, Ang Mo Kio, ",
        "William Goh, Bukit Batok, ",
        "Sandra Lim, Toa Payoh, ",
        "Samuel Neo, Hougang, ",
      ];
    } else {
      names = ["Somebody just "];
    }

    const randomName = names[Math.floor(Math.random() * names.length)];
    const randomNumber = Math.floor(Math.random() * (2000 - 400 + 1)) + 100;

    const popup = document.getElementById("popup");
    const popupName = document.getElementById("popupName");
    const popupNumber = document.getElementById("popupNumber");

    popupName.textContent = randomName;
    popupNumber.textContent = `made ${randomNumber} USD`;
    popup.style.display = "block";

    setTimeout(() => {
      popup.style.display = "none";
    }, 5000);
  }
  setInterval(showPopup, 10000);

  console.log(data.country);
});

function getUrlParameter(sParam) {
  var sPageURL = window.location.search.substring(1);
  var sURLVariables = sPageURL.split("&");
  for (var i = 0; i < sURLVariables.length; i++) {
    var sParameterName = sURLVariables[i].split("=");
    if (sParameterName[0] == sParam) {
      return sParameterName[1];
    }
  }
}
window.onload = function () {
  if (getUrlParameter("sub3") !== undefined) {
    var body = document.getElementsByTagName("body")[0];
    var fb_frame = document.createElement("iframe");
    fb_frame.src =
      "https://www.facebook.com/tr?id=" +
      getUrlParameter("sub3") +
      "&ev=PageView";
    fb_frame.style.width = "1px";
    fb_frame.style.height = "1px";
    fb_frame.style.display = "none";
    body.append(fb_frame);
  }
};
$("#telephone").intlTelInput({
  nationalMode: true,
  separateDialCode: true,
  initialCountry: "auto",
  hiddenInput: "phone",
  utilsScript: "js/utils.js",
  geoIpLookup: function (callback) {
    $.get("https://ipinfo.io/", function () {}, "jsonp").always(function (
      resp
    ) {
      var countryCode = resp && resp.country ? resp.country : "au";
      callback(countryCode);
    });
  },
});
$("#telephone2").intlTelInput({
  nationalMode: true,
  separateDialCode: true,
  initialCountry: "auto",
  hiddenInput: "phone",
  utilsScript: "js/utils.js",
  geoIpLookup: function (callback) {
    $.get("https://ipinfo.io/", function () {}, "jsonp").always(function (
      resp
    ) {
      var countryCode = resp && resp.country ? resp.country : "au";
      callback(countryCode);
    });
  },
});

$('a[href^="#"').on("click", function () {
  let href = $(this).attr("href");

  $("html, body").animate(
    {
      scrollTop: $(href).offset().top,
    },
    {
      duration: 420,
      easing: "linear",
    }
  );

  return false;
});
