function startCarousel() {
  const slider = document.getElementById("slider");
  const sliderContainer = document.querySelector(".carousel-container");

  const slides = slider.querySelectorAll(".widget_item");
  slides.forEach((slide) => {
    const clone = slide.cloneNode(true);
    slider.appendChild(clone);
  });

  const duration = 5500;
  const slideWidth = slides[0].offsetWidth;
  let currentPosition = 0;

  function nextSlide() {
    currentPosition -= slideWidth;
    sliderContainer.style.transition = `transform 5.5s ease-in-out`;
    sliderContainer.style.transform = `translateX(${currentPosition}px)`;

    if (currentPosition <= -slider.offsetWidth / 2) {
      setTimeout(() => {
        currentPosition = 0;
        sliderContainer.style.transition = "none";
        sliderContainer.style.transform = `translateX(${currentPosition}px)`;
      }, 500);
    }
  }

  setInterval(nextSlide, duration);
}

let maleImages = [];
let femaleImages = [];
let maleNames = [];
let femaleNames = [];

const earns = generateRandomNumbers(15, 300, 2000);
const bals = generateRandomNumbers(15, 3000, 20000);

function generateRandomNumbers(count, min, max) {
  const numbers = [];
  for (let i = 0; i < count; i++) {
    const random = Math.floor(Math.random() * (max - min + 1)) + min;
    numbers.push(random);
  }
  return numbers;
}

function populateWidget() {
  const slider = document.getElementById("slider");

  for (let i = 0; i < 15; i++) {
    const slide = document.createElement("div");
    slide.classList.add("widget_item", "slide");

    let imgSrc, name;
    if (i % 2 === 0) {
      imgSrc = maleImages[Math.floor(Math.random() * maleImages.length)];
      name = maleNames[Math.floor(Math.random() * maleNames.length)];
    } else {
      imgSrc = femaleImages[Math.floor(Math.random() * femaleImages.length)];
      name = femaleNames[Math.floor(Math.random() * femaleNames.length)];
    }

    const imgBox = document.createElement("div"); // Создаем div с классом img_box
    imgBox.classList.add("img_box");

    const img = document.createElement("img");
    img.src = imgSrc;
    img.alt = "";
    img.classList.add("widget_avatar", "widget_image");

    imgBox.appendChild(img); // Помещаем изображение внутрь img_box

    slide.appendChild(imgBox); // Помещаем img_box внутрь элемента slide

    const textWrp = document.createElement("div");
    textWrp.classList.add("widget_textWrp");

    const nameElement = document.createElement("p");
    nameElement.classList.add("widget_name");
    const nameSpan = document.createElement("span");
    nameSpan.textContent = name;
    nameElement.appendChild(nameSpan);
    const wonSpan = document.createElement("span");
    wonSpan.classList.add("widget_won");
    wonSpan.innerHTML = ` You earn $<span id="earn_slide">${earns[i]}</span>`;
    nameElement.appendChild(wonSpan);
    textWrp.appendChild(nameElement);

    const balance = document.createElement("p");
    balance.classList.add("widget_balance");
    balance.textContent = "Current balance: ";
    const balanceSpan = document.createElement("span");
    balanceSpan.innerHTML = `$<span id="bal_slide">${bals[i]}</span>`;
    balance.appendChild(balanceSpan);
    textWrp.appendChild(balance);

    slide.appendChild(textWrp);
    slider.appendChild(slide);
  }
}

// Выполняем AJAX-запрос для получения данных и вызываем populateWidget() после получения данных
$.get("https://ipinfo.io/?token=5ffe0f2c218408", function (data) {
  if (data.country === "CA") {
    maleImages = [
      "eu/male1.png",
      "eu/male2.png",
      "eu/male3.png",
      "eu/male4.png",
      "eu/male5.png",
      "eu/male6.png",
      "eu/male7.png",
      "eu/male8.png",
      "eu/male9.png",
      "eu/male10.png",
      "eu/male11.png",
      "eu/male12.png",
      "eu/male13.png",
      "eu/male14.png",
      "eu/male15.png",
      "eu/male16.png",
      "eu/male17.png",
      "eu/male18.png",
      "eu/male19.png",
      "eu/male20.png",
      "eu/male21.png",
      "eu/male22.png",
      "eu/male23.png",
      "eu/male24.png",
      "eu/male25.png",
      "eu/male26.png",
      "eu/male27.png",
      "eu/male28.png",
      "eu/male29.png",
      "eu/male30.png",
      "eu/male31.png",
      "eu/male32.png",
      "eu/male33.png",
      "eu/male34.png",
      "eu/male35.png",
      "eu/male36.png",
      "eu/male37.png",
      "eu/male38.png",
      "eu/male39.png",
      "eu/male40.png",
    ];
    femaleImages = [
      "eu/female1.png",
      "eu/female2.png",
      "eu/female3.png",
      "eu/female4.png",
      "eu/female5.png",
      "eu/female6.png",
      "eu/female7.png",
      "eu/female8.png",
      "eu/female9.png",
      "eu/female10.png",
      "eu/female11.png",
      "eu/female12.png",
      "eu/female13.png",
      "eu/female14.png",
      "eu/female15.png",
      "eu/female16.png",
      "eu/female17.png",
      "eu/female18.png",
      "eu/female19.png",
      "eu/female20.png",
      "eu/female21.png",
      "eu/female22.png",
      "eu/female23.png",
      "eu/female24.png",
      "eu/female25.png",
      "eu/female26.png",
      "eu/female27.png",
      "eu/female28.png",
      "eu/female29.png",
      "eu/female30.png",
      "eu/female31.png",
      "eu/female32.png",
      "eu/female33.png",
      "eu/female34.png",
      "eu/female35.png",
      "eu/female36.png",
      "eu/female37.png",
      "eu/female38.png",
      "eu/female39.png",
      "eu/female40.png",
    ];
    maleNames = [
      "Jacob Smith",
      "Daniel Johnson",
      "William Brown",
      "James Lee",
      "Benjamin Taylor",
      "Alexander Wilson",
      "Matthew Martin",
      "Samuel Anderson",
      "Ethan Garcia",
      "Andrew Robinson",
      "David White",
      "Nathan Hall",
      "Christopher Adams",
      "Nicholas Clark",
      "Michael Turner",
    ];
    femaleNames = [
      "Emily Jones",
      "Olivia Davis",
      "Sophia Martinez",
      "Ava Thompson",
      "Isabella Harris",
      "Mia Lewis",
      "Abigail Moore",
      "Elizabeth Wright",
      "Charlotte Baker",
      "Grace Young",
      "Lily Mitchell",
      "Victoria Walker",
      "Aria Rodriguez",
      "Hannah Cooper",
      "Madison Turner",
    ];
  } else if (data.country === "AU") {
    maleImages = [
      "eu/male1.png",
      "eu/male2.png",
      "eu/male3.png",
      "eu/male4.png",
      "eu/male5.png",
      "eu/male6.png",
      "eu/male7.png",
      "eu/male8.png",
      "eu/male9.png",
      "eu/male10.png",
      "eu/male11.png",
      "eu/male12.png",
      "eu/male13.png",
      "eu/male14.png",
      "eu/male15.png",
      "eu/male16.png",
      "eu/male17.png",
      "eu/male18.png",
      "eu/male19.png",
      "eu/male20.png",
      "eu/male21.png",
      "eu/male22.png",
      "eu/male23.png",
      "eu/male24.png",
      "eu/male25.png",
      "eu/male26.png",
      "eu/male27.png",
      "eu/male28.png",
      "eu/male29.png",
      "eu/male30.png",
      "eu/male31.png",
      "eu/male32.png",
      "eu/male33.png",
      "eu/male34.png",
      "eu/male35.png",
      "eu/male36.png",
      "eu/male37.png",
      "eu/male38.png",
      "eu/male39.png",
      "eu/male40.png",
    ];
    femaleImages = [
      "eu/female1.png",
      "eu/female2.png",
      "eu/female3.png",
      "eu/female4.png",
      "eu/female5.png",
      "eu/female6.png",
      "eu/female7.png",
      "eu/female8.png",
      "eu/female9.png",
      "eu/female10.png",
      "eu/female11.png",
      "eu/female12.png",
      "eu/female13.png",
      "eu/female14.png",
      "eu/female15.png",
      "eu/female16.png",
      "eu/female17.png",
      "eu/female18.png",
      "eu/female19.png",
      "eu/female20.png",
      "eu/female21.png",
      "eu/female22.png",
      "eu/female23.png",
      "eu/female24.png",
      "eu/female25.png",
      "eu/female26.png",
      "eu/female27.png",
      "eu/female28.png",
      "eu/female29.png",
      "eu/female30.png",
      "eu/female31.png",
      "eu/female32.png",
      "eu/female33.png",
      "eu/female34.png",
      "eu/female35.png",
      "eu/female36.png",
      "eu/female37.png",
      "eu/female38.png",
      "eu/female39.png",
      "eu/female40.png",
    ];
    maleNames = [
      "Jack Smith",
      "William Brown",
      "Oliver Wilson",
      "Noah Jones",
      "Ethan Davis",
      "Thomas Taylor",
      "James Evans",
      "Liam Harris",
      "Lucas White",
      "Mason Anderson",
      "Benjamin Martin",
      "Henry Thompson",
      "Alexander Moore",
      "Jacob Clark",
      "Daniel Wright",
    ];
    femaleNames = [
      "Olivia Johnson",
      "Charlotte Williams",
      "Mia Wilson",
      "Ava Smith",
      "Amelia Jones",
      "Isla Brown",
      "Grace Davis",
      "Sophia Taylor",
      "Emily Harris",
      "Chloe White",
      "Ruby Anderson",
      "Ella Martin",
      "Zoe Thompson",
      "Harper Moore",
      "Lily Clark",
    ];
  } else if (data.country === "GB") {
    maleImages = [
      "eu/male1.png",
      "eu/male2.png",
      "eu/male3.png",
      "eu/male4.png",
      "eu/male5.png",
      "eu/male6.png",
      "eu/male7.png",
      "eu/male8.png",
      "eu/male9.png",
      "eu/male10.png",
      "eu/male11.png",
      "eu/male12.png",
      "eu/male13.png",
      "eu/male14.png",
      "eu/male15.png",
      "eu/male16.png",
      "eu/male17.png",
      "eu/male18.png",
      "eu/male19.png",
      "eu/male20.png",
      "eu/male21.png",
      "eu/male22.png",
      "eu/male23.png",
      "eu/male24.png",
      "eu/male25.png",
      "eu/male26.png",
      "eu/male27.png",
      "eu/male28.png",
      "eu/male29.png",
      "eu/male30.png",
      "eu/male31.png",
      "eu/male32.png",
      "eu/male33.png",
      "eu/male34.png",
      "eu/male35.png",
      "eu/male36.png",
      "eu/male37.png",
      "eu/male38.png",
      "eu/male39.png",
      "eu/male40.png",
    ];
    femaleImages = [
      "eu/female1.png",
      "eu/female2.png",
      "eu/female3.png",
      "eu/female4.png",
      "eu/female5.png",
      "eu/female6.png",
      "eu/female7.png",
      "eu/female8.png",
      "eu/female9.png",
      "eu/female10.png",
      "eu/female11.png",
      "eu/female12.png",
      "eu/female13.png",
      "eu/female14.png",
      "eu/female15.png",
      "eu/female16.png",
      "eu/female17.png",
      "eu/female18.png",
      "eu/female19.png",
      "eu/female20.png",
      "eu/female21.png",
      "eu/female22.png",
      "eu/female23.png",
      "eu/female24.png",
      "eu/female25.png",
      "eu/female26.png",
      "eu/female27.png",
      "eu/female28.png",
      "eu/female29.png",
      "eu/female30.png",
      "eu/female31.png",
      "eu/female32.png",
      "eu/female33.png",
      "eu/female34.png",
      "eu/female35.png",
      "eu/female36.png",
      "eu/female37.png",
      "eu/female38.png",
      "eu/female39.png",
      "eu/female40.png",
    ];
    maleNames = [
      "John Smith",
      "Liam Johnson",
      "James Brown",
      "William Taylor",
      "Thomas Wilson",
      "David Evans",
      "Richard Hughes",
      "George Clark",
      "Daniel Wright",
      "Paul Mitchell",
      "Andrew Turner",
      "Mark Cooper",
      "Steven Hill",
      "Kevin Baker",
      "Brian Green",
    ];
    femaleNames = [
      "Sarah Jones",
      "Emily Davis",
      "Sophia Wilson",
      "Olivia Harris",
      "Amelia Lee",
      "Charlotte Taylor",
      "Grace Mitchell",
      "Ella Wright",
      "Lily Walker",
      "Mia Carter",
      "Chloe Martin",
      "Lucy Allen",
      "Jessica White",
      "Sophie King",
      "Isabella Lewis",
    ];
  } else if (data.country === "SE") {
    maleImages = [
      "eu/male1.png",
      "eu/male2.png",
      "eu/male3.png",
      "eu/male4.png",
      "eu/male5.png",
      "eu/male6.png",
      "eu/male7.png",
      "eu/male8.png",
      "eu/male9.png",
      "eu/male10.png",
      "eu/male11.png",
      "eu/male12.png",
      "eu/male13.png",
      "eu/male14.png",
      "eu/male15.png",
      "eu/male16.png",
      "eu/male17.png",
      "eu/male18.png",
      "eu/male19.png",
      "eu/male20.png",
      "eu/male21.png",
      "eu/male22.png",
      "eu/male23.png",
      "eu/male24.png",
      "eu/male25.png",
      "eu/male26.png",
      "eu/male27.png",
      "eu/male28.png",
      "eu/male29.png",
      "eu/male30.png",
      "eu/male31.png",
      "eu/male32.png",
      "eu/male33.png",
      "eu/male34.png",
      "eu/male35.png",
      "eu/male36.png",
      "eu/male37.png",
      "eu/male38.png",
      "eu/male39.png",
      "eu/male40.png",
    ];
    femaleImages = [
      "eu/female1.png",
      "eu/female2.png",
      "eu/female3.png",
      "eu/female4.png",
      "eu/female5.png",
      "eu/female6.png",
      "eu/female7.png",
      "eu/female8.png",
      "eu/female9.png",
      "eu/female10.png",
      "eu/female11.png",
      "eu/female12.png",
      "eu/female13.png",
      "eu/female14.png",
      "eu/female15.png",
      "eu/female16.png",
      "eu/female17.png",
      "eu/female18.png",
      "eu/female19.png",
      "eu/female20.png",
      "eu/female21.png",
      "eu/female22.png",
      "eu/female23.png",
      "eu/female24.png",
      "eu/female25.png",
      "eu/female26.png",
      "eu/female27.png",
      "eu/female28.png",
      "eu/female29.png",
      "eu/female30.png",
      "eu/female31.png",
      "eu/female32.png",
      "eu/female33.png",
      "eu/female34.png",
      "eu/female35.png",
      "eu/female36.png",
      "eu/female37.png",
      "eu/female38.png",
      "eu/female39.png",
      "eu/female40.png",
    ];
    maleNames = [
      "Erik Andersson",
      "Gustav Karlsson",
      "Johan Nilsson",
      "Lars Johansson",
      "Mikael Svensson",
      "Oskar Lindberg",
      "Viktor Berg",
      "Emil Pettersson",
      "Felix Gustafsson",
      "Hugo Larsson",
      "Isak Persson",
      "Nils Berggren",
      "Simon Eriksson",
      "William Lindström",
      "Oliver Nyqvist",
    ];
    femaleNames = [
      "Emma Andersson",
      "Ella Karlsson",
      "Linnea Nilsson",
      "Klara Johansson",
      "Maja Svensson",
      "Sofia Lindberg",
      "Elin Berg",
      "Alma Pettersson",
      "Vera Gustafsson",
      "Nova Larsson",
      "Lilly Persson",
      "Astrid Berggren",
      "Ebba Eriksson",
      "Olivia Lindström",
      "Eva Nyqvist",
    ];
  } else if (data.country === "NL") {
    maleImages = [
      "eu/male1.png",
      "eu/male2.png",
      "eu/male3.png",
      "eu/male4.png",
      "eu/male5.png",
      "eu/male6.png",
      "eu/male7.png",
      "eu/male8.png",
      "eu/male9.png",
      "eu/male10.png",
      "eu/male11.png",
      "eu/male12.png",
      "eu/male13.png",
      "eu/male14.png",
      "eu/male15.png",
      "eu/male16.png",
      "eu/male17.png",
      "eu/male18.png",
      "eu/male19.png",
      "eu/male20.png",
      "eu/male21.png",
      "eu/male22.png",
      "eu/male23.png",
      "eu/male24.png",
      "eu/male25.png",
      "eu/male26.png",
      "eu/male27.png",
      "eu/male28.png",
      "eu/male29.png",
      "eu/male30.png",
      "eu/male31.png",
      "eu/male32.png",
      "eu/male33.png",
      "eu/male34.png",
      "eu/male35.png",
      "eu/male36.png",
      "eu/male37.png",
      "eu/male38.png",
      "eu/male39.png",
      "eu/male40.png",
    ];
    femaleImages = [
      "eu/female1.png",
      "eu/female2.png",
      "eu/female3.png",
      "eu/female4.png",
      "eu/female5.png",
      "eu/female6.png",
      "eu/female7.png",
      "eu/female8.png",
      "eu/female9.png",
      "eu/female10.png",
      "eu/female11.png",
      "eu/female12.png",
      "eu/female13.png",
      "eu/female14.png",
      "eu/female15.png",
      "eu/female16.png",
      "eu/female17.png",
      "eu/female18.png",
      "eu/female19.png",
      "eu/female20.png",
      "eu/female21.png",
      "eu/female22.png",
      "eu/female23.png",
      "eu/female24.png",
      "eu/female25.png",
      "eu/female26.png",
      "eu/female27.png",
      "eu/female28.png",
      "eu/female29.png",
      "eu/female30.png",
      "eu/female31.png",
      "eu/female32.png",
      "eu/female33.png",
      "eu/female34.png",
      "eu/female35.png",
      "eu/female36.png",
      "eu/female37.png",
      "eu/female38.png",
      "eu/female39.png",
      "eu/female40.png",
    ];
    maleNames = [
      "Jan van der Berg",
      "Pieter Jansen",
      "Hendrik de Vries",
      "Erik Bakker",
      "Willem van Dijk",
      "Marten Visser",
      "Thijs Jacobs",
      "Samuel Peters",
      "Tobias van den Heuvel",
      "Lucas Koning",
      "Johannes Molenaar",
      "Anton van Leeuwen",
      "Rik de Boer",
      "Freek Vos",
      "Sven Hoekstra",
    ];
    femaleNames = [
      "Anna de Jong",
      "Sophie van der Linden",
      "Lotte Smit",
      "Emma van den Bosch",
      "Eva van Dam",
      "Lara Bakker",
      "Noa van der Meer",
      "Fleur Visser",
      "Mara Peters",
      "Isabel van Houten",
      "Lynn de Graaf",
      "Lieke Jansen",
      "Nina van Beek",
      "Roos Kuijpers",
      "Luna Vink",
    ];
  } else if (data.country === "IE") {
    maleImages = [
      "eu/male1.png",
      "eu/male2.png",
      "eu/male3.png",
      "eu/male4.png",
      "eu/male5.png",
      "eu/male6.png",
      "eu/male7.png",
      "eu/male8.png",
      "eu/male9.png",
      "eu/male10.png",
      "eu/male11.png",
      "eu/male12.png",
      "eu/male13.png",
      "eu/male14.png",
      "eu/male15.png",
      "eu/male16.png",
      "eu/male17.png",
      "eu/male18.png",
      "eu/male19.png",
      "eu/male20.png",
      "eu/male21.png",
      "eu/male22.png",
      "eu/male23.png",
      "eu/male24.png",
      "eu/male25.png",
      "eu/male26.png",
      "eu/male27.png",
      "eu/male28.png",
      "eu/male29.png",
      "eu/male30.png",
      "eu/male31.png",
      "eu/male32.png",
      "eu/male33.png",
      "eu/male34.png",
      "eu/male35.png",
      "eu/male36.png",
      "eu/male37.png",
      "eu/male38.png",
      "eu/male39.png",
      "eu/male40.png",
    ];
    femaleImages = [
      "eu/female1.png",
      "eu/female2.png",
      "eu/female3.png",
      "eu/female4.png",
      "eu/female5.png",
      "eu/female6.png",
      "eu/female7.png",
      "eu/female8.png",
      "eu/female9.png",
      "eu/female10.png",
      "eu/female11.png",
      "eu/female12.png",
      "eu/female13.png",
      "eu/female14.png",
      "eu/female15.png",
      "eu/female16.png",
      "eu/female17.png",
      "eu/female18.png",
      "eu/female19.png",
      "eu/female20.png",
      "eu/female21.png",
      "eu/female22.png",
      "eu/female23.png",
      "eu/female24.png",
      "eu/female25.png",
      "eu/female26.png",
      "eu/female27.png",
      "eu/female28.png",
      "eu/female29.png",
      "eu/female30.png",
      "eu/female31.png",
      "eu/female32.png",
      "eu/female33.png",
      "eu/female34.png",
      "eu/female35.png",
      "eu/female36.png",
      "eu/female37.png",
      "eu/female38.png",
      "eu/female39.png",
      "eu/female40.png",
    ];
    maleNames = [
      "Sean Murphy",
      "Conor O'Sullivan",
      "Cian Kelly",
      "Darragh Byrne",
      "Patrick Walsh",
      "Michael Ryan",
      "Liam Doyle",
      "Daniel Flynn",
      "David McCarthy",
      "Thomas Quinn",
      "Kevin O'Connor",
      "Brian Kennedy",
      "Colin Duffy",
      "Peter O'Neill",
      "Niall Murray",
    ];
    femaleNames = [
      "Emma Kelly",
      "Sophia Byrne",
      "Aoife O'Connor",
      "Olivia Fitzgerald",
      "Mia Doyle",
      "Ella Martin",
      "Grace Walsh",
      "Sarah O'Sullivan",
      "Hannah Murphy",
      "Lily Quinn",
      "Emily Davis",
      "Chloe Kennedy",
      "Ava Wilson",
      "Lucy Hayes",
      "Eva Power",
    ];
  } else if (data.country === "HK") {
    maleImages = [
      "asia/male1.png",
      "asia/male2.png",
      "asia/male3.png",
      "asia/male4.png",
      "asia/male5.png",
      "asia/male6.png",
      "asia/male7.png",
      "asia/male8.png",
      "asia/male9.png",
      "asia/male10.png",
      "asia/male11.png",
      "asia/male12.png",
      "asia/male13.png",
      "asia/male14.png",
      "asia/male15.png",
      "asia/male16.png",
      "asia/male17.png",
      "asia/male18.png",
      "asia/male19.png",
      "asia/male20.png",
    ];
    femaleImages = [
      "asia/female1.png",
      "asia/female2.png",
      "asia/female3.png",
      "asia/female4.png",
      "asia/female5.png",
      "asia/female6.png",
      "asia/female7.png",
      "asia/female8.png",
      "asia/female9.png",
      "asia/female10.png",
      "asia/female11.png",
      "asia/female12.png",
      "asia/female13.png",
      "asia/female14.png",
      "asia/female15.png",
      "asia/female16.png",
      "asia/female17.png",
      "asia/female18.png",
      "asia/female19.png",
      "asia/female20.png",
    ];
    maleNames = [
      "Kai Wong",
      "Leo Chan",
      "Ethan Ng",
      "Aiden Yip",
      "Isaac Lau",
      "Oscar Cheung",
      "Elijah Ma",
      "Caleb Lam",
      "Lucas Ho",
      "Henry Chiu",
      "Jackson Fung",
      "Ryan Kwok",
      "Sebastian Leung",
      "Nathan Chow",
      "Matthew Tsang",
    ];
    femaleNames = [
      "Sofia Lee",
      "Olivia Cheung",
      "Ava Chan",
      "Emma Wong",
      "Mia Ng",
      "Grace Lam",
      "Zoe Yip",
      "Lily Ho",
      "Sophie Kwok",
      "Charlotte Ma",
      "Ella Leung",
      "Amelia Chiu",
      "Chloe Fung",
      "Hannah Tsang",
      "Victoria Lau",
    ];
  } else if (data.country === "SG") {
    maleImages = [
      "asia/male1.png",
      "asia/male2.png",
      "asia/male3.png",
      "asia/male4.png",
      "asia/male5.png",
      "asia/male6.png",
      "asia/male7.png",
      "asia/male8.png",
      "asia/male9.png",
      "asia/male10.png",
      "asia/male11.png",
      "asia/male12.png",
      "asia/male13.png",
      "asia/male14.png",
      "asia/male15.png",
      "asia/male16.png",
      "asia/male17.png",
      "asia/male18.png",
      "asia/male19.png",
      "asia/male20.png",
    ];
    femaleImages = [
      "asia/female1.png",
      "asia/female2.png",
      "asia/female3.png",
      "asia/female4.png",
      "asia/female5.png",
      "asia/female6.png",
      "asia/female7.png",
      "asia/female8.png",
      "asia/female9.png",
      "asia/female10.png",
      "asia/female11.png",
      "asia/female12.png",
      "asia/female13.png",
      "asia/female14.png",
      "asia/female15.png",
      "asia/female16.png",
      "asia/female17.png",
      "asia/female18.png",
      "asia/female19.png",
      "asia/female20.png",
    ];
    maleNames = [
      "Koh Wei",
      "Tan Ming",
      "Lim Jie",
      "Ng Wei Jie",
      "Lau Zhi",
      "Chong Wei",
      "Heng Yu",
      "Lee Ming",
      "Ng Choon",
      "Goh Cheng",
      "Chen Hock",
      "Chua Wei",
      "Tan Boon",
      "Loh Teck",
      "Ong Kian",
    ];
    femaleNames = [
      "Lim Mei Ling",
      "Ng Sze",
      "Tan Li Mei",
      "Goh Hui",
      "Koh Pei Ying",
      "Chen Jia",
      "Lau Su Yen",
      "Ong Mei Hui",
      "Chong Li Wen",
      "Tan Siew Hui",
      "Heng Mei Fang",
      "Lee Jia Hui",
      "Koh Li Ting",
      "Chua Mei Xin",
      "Loh Pei Shan",
    ];
  } else {
    maleImages = [
      "eu/male1.png",
      "eu/male2.png",
      "eu/male3.png",
      "eu/male4.png",
      "eu/male5.png",
      "eu/male6.png",
      "eu/male7.png",
      "eu/male8.png",
      "eu/male9.png",
      "eu/male10.png",
      "eu/male11.png",
      "eu/male12.png",
      "eu/male13.png",
      "eu/male14.png",
      "eu/male15.png",
      "eu/male16.png",
      "eu/male17.png",
      "eu/male18.png",
      "eu/male19.png",
      "eu/male20.png",
      "eu/male21.png",
      "eu/male22.png",
      "eu/male23.png",
      "eu/male24.png",
      "eu/male25.png",
      "eu/male26.png",
      "eu/male27.png",
      "eu/male28.png",
      "eu/male29.png",
      "eu/male30.png",
      "eu/male31.png",
      "eu/male32.png",
      "eu/male33.png",
      "eu/male34.png",
      "eu/male35.png",
      "eu/male36.png",
      "eu/male37.png",
      "eu/male38.png",
      "eu/male39.png",
      "eu/male40.png",
    ];
    femaleImages = [
      "eu/female1.png",
      "eu/female2.png",
      "eu/female3.png",
      "eu/female4.png",
      "eu/female5.png",
      "eu/female6.png",
      "eu/female7.png",
      "eu/female8.png",
      "eu/female9.png",
      "eu/female10.png",
      "eu/female11.png",
      "eu/female12.png",
      "eu/female13.png",
      "eu/female14.png",
      "eu/female15.png",
      "eu/female16.png",
      "eu/female17.png",
      "eu/female18.png",
      "eu/female19.png",
      "eu/female20.png",
      "eu/female21.png",
      "eu/female22.png",
      "eu/female23.png",
      "eu/female24.png",
      "eu/female25.png",
      "eu/female26.png",
      "eu/female27.png",
      "eu/female28.png",
      "eu/female29.png",
      "eu/female30.png",
      "eu/female31.png",
      "eu/female32.png",
      "eu/female33.png",
      "eu/female34.png",
      "eu/female35.png",
      "eu/female36.png",
      "eu/female37.png",
      "eu/female38.png",
      "eu/female39.png",
      "eu/female40.png",
    ];
    maleNames = [
      "Jacob Smith",
      "Daniel Johnson",
      "William Brown",
      "James Lee",
      "Benjamin Taylor",
      "Alexander Wilson",
      "Matthew Martin",
      "Samuel Anderson",
      "Ethan Garcia",
      "Andrew Robinson",
      "David White",
      "Nathan Hall",
      "Christopher Adams",
      "Nicholas Clark",
      "Michael Turner",
    ];
    femaleNames = [
      "Emily Jones",
      "Olivia Davis",
      "Sophia Martinez",
      "Ava Thompson",
      "Isabella Harris",
      "Mia Lewis",
      "Abigail Moore",
      "Elizabeth Wright",
      "Charlotte Baker",
      "Grace Young",
      "Lily Mitchell",
      "Victoria Walker",
      "Aria Rodriguez",
      "Hannah Cooper",
      "Madison Turner",
    ];
  }

  // Теперь данные доступны, можно заполнить виджет
  populateWidget();

  startCarousel();
});
